# Generated by Django 5.0.1 on 2024-01-04 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Pais')),
                ('flag', models.ImageField(upload_to='banderas/')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Piso')),
                ('description', models.CharField(max_length=250, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Pisos',
            },
        ),
        migrations.CreateModel(
            name='Languagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Lenguaje')),
            ],
            options={
                'verbose_name': 'Lenguaje',
                'verbose_name_plural': 'Lenguajes',
            },
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Museo')),
                ('image', models.ImageField(upload_to='museos/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.countries')),
                ('floor', models.ManyToManyField(to='country.floor')),
                ('languague', models.ManyToManyField(to='country.languagues')),
            ],
            options={
                'verbose_name': 'Museo',
                'verbose_name_plural': 'Museos',
            },
        ),
    ]
