# Generated by Django 5.0.1 on 2024-01-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languagues',
            new_name='Languages',
        ),
    ]
