# Generated by Django 5.0.1 on 2024-01-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_rename_languagues_languages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'Paises'},
        ),
        migrations.RenameField(
            model_name='museum',
            old_name='languague',
            new_name='language',
        ),
    ]
